fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/voxpupuli/puppet-systemd.git"
    extlib: "https://github.com/voxpupuli/puppet-extlib.git"
