fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: '4.4.0'
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: '1.1.0'
    file_concat:
      repo: 'git://github.com/electrical/puppet-lib-file_concat.git'
      ref: '1.0.1'
  symlinks:
    unbound: "#{source_dir}"
