---
.travis.yml:
  extras:
    - rvm: 2.5.1
      bundler_args: --without development
      env: BEAKER_set=docker/ubuntu-14.04 CHECK=beaker
      services: docker
      sudo: required
    - rvm: 2.5.1
      bundler_args: --without development
      env: BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
      services: docker
      sudo: required
    - rvm: 2.5.1
      bundler_args: --without development
      env: BEAKER_set=docker/centos-6 CHECK=beaker
      services: docker
      sudo: required
    - rvm: 2.5.1
      bundler_args: --without development
      env: BEAKER_set=docker/centos-7 CHECK=beaker
      services: docker
      sudo: required
    - rvm: 2.5.1
      bundler_args: --without development
      env: BEAKER_set=docker/debian-8 CHECK=beaker
      services: docker
      sudo: required
