name    'zleslie-unbound'
version '1.0.0'
source 'git://github.com/xaque208/puppet-unbound.git'
author 'zleslie'
license 'Apache License Version 2.0'
summary 'Puppet Unbound management module'
description 'A module to deploy and manage the Unbound caching resolver'
project_page 'https://github.com/xaque208/puppet-unbound'
dependency 'puppetlabs/concat'
